[programs.localnet]
solclassis = "Hs68KZpxy8yxem4VhMXerpBQFK2YWJCbXMcYCDTNJTF3"

[programs.devnet]
solclassis = "Hs68KZpxy8yxem4VhMXerpBQFK2YWJCbXMcYCDTNJTF3"

[provider]
cluster = "devnet"
wallet = "/home/minji/.config/solana/id.json"
program_space = 2048000  # 2MB

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
